FROM node:22-alpine
RUN npm install -g pnpm
WORKDIR /app
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY packages/shared/package.json ./packages/shared/
COPY apps/frontend/package.json ./apps/frontend/
RUN pnpm install
COPY . .
WORKDIR /app/apps/frontend
CMD ["pnpm", "dev", "--host"]
