http:
  routers:
    api:
      rule: "Host(`tracker.kirrrusha.ru`) && PathPrefix(`/api`)"
      entryPoints: [websecure]
      service: api-backend
      tls:
        certResolver: letsencrypt
      middlewares: [strip-api]
      priority: 100

    frontend:
      rule: "Host(`tracker.kirrrusha.ru`)"
      entryPoints: [websecure]
      service: frontend-nginx
      tls:
        certResolver: letsencrypt
      priority: 1

  middlewares:
    strip-api:
      stripPrefix:
        prefixes: ["/api"]

  services:
    api-backend:
      loadBalancer:
        servers:
          - url: "http://backend:4000"

    frontend-nginx:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
